config/routes.rb
Rails.application.routes.draw do
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all

# Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"

  resources :users, only: [:testdesk] do
    get "/testdesk", to: "pages#testdesk"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :games, only: [:create, :show] do
    member do
      post "/start", to: "games#start"
      post "/end", to: "games#end"
      post "/next_question", to: "games#next_question"
    end
  end

  resources :participations, only: [] do
    member do
      post "/ready", to: "participations#ready"
      post "/answer", to: "answers#answer"
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div id="background-homepage">
  <%= render "shared/navbarhome" %>
  <div class="container" >
    <div class="player-mode">
      <%= image_tag "logo/logo.gif", id:"logo-homepage" %>
      <div class="player-mode-btn">
        <div class="big-yellow-btn">
          <i class="fa-solid fa-user"></i>
          <p class="yellow">Solo</p>
        </div>
        <div data-controller="check-user-session">
          <% if user_signed_in? %>
            <%= link_to games_path, data: { turbo_method: :post } do %>
                <div class="big-yellow-btn">
                  <i data-action="click->check-user-session#desactivate_button"class="fa-solid fa-users"></i>
                  <p data-check-user-session-target="button">Multijoueur</p>
                </div>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, data: { turbo_method: :get } do %>
                <div class="big-yellow-btn">
                  <i data-action="click->check-user-session#desactivate_button"class="fa-solid fa-users"></i>
                  <p data-check-user-session-target="button">Multijoueur</p>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <%= image_tag "babyvira/baby-lain.gif", id:"gif-homepage"%>
    </div>
  </div>
</div>

app/views/pages/testdesk.html.erb
<div class="container">
  <h1>TEST</h1>
  <div id="players-desk-1round">
    <div id="player-desk-1round">
      <div>
        <p id="player-nickname-1round">Player Nickname</p>
      </div>
      <div id="card-point-1round">
        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

      </div>
    </div>

    <div id="player-desk-1round">
      <div>
        <p id="player-nickname-1round">Player Nickname</p>
      </div>
      <div id="card-point-1round">
        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

      </div>
    </div>

    <div id="player-desk-1round">
      <div>
        <p id="player-nickname-1round">Player Nickname</p>
      </div>
      <div id="card-point-1round">
        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

      </div>
    </div>

    <div id="player-desk-1round">
      <div>
        <p id="player-nickname-1round">Player Nickname</p>
      </div>
      <div id="card-point-1round">
        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-gray">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

        <div class="point-1round-orange">
        </div>

      </div>
    </div>
  </div>
</div>