config/routes.rb
Rails.application.routes.draw do
  # get 'errors/not_found'
  # get 'errors/internal_server_error'
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all

# Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"

  resources :users, only: [:testdesk] do
    get "/testdesk", to: "pages#testdesk"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :games, only: [:create, :show] do
    member do
      post "/start", to: "games#start"
      post "/end", to: "games#end"
      post "/next_question", to: "games#next_question"
    end
  end

  resources :participations, only: [] do
    member do
      post "/ready", to: "participations#ready"
      post "/answer", to: "answers#answer"
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user

  has_many :participations, dependent: :destroy
  has_many :players, through: :participations, source: :user
  has_many :game_questions, dependent: :destroy
  has_many :questions, through: :game_questions

  def current_question
    self.questions[self.question_number]
  end

  def previous_question
    self.questions[self.question_number - 1]
  end

  def players_ready?
    participations.map(&:ready).all?
  end

  def started?
    status == "running"
  end

  def ended?
    status == "ended"
  end

  def current_attempts
    current_question.game_questions.where(game: self).flat_map(&:attempts)
  end

  def previous_attempts
    previous_question.game_questions.where(game: self).flat_map(&:attempts)
  end

  def all_attempts_false
    current_attempts.all? { |at| at.success == false } && current_attempts.count == participations.count
  end

  def any_attempts_correct?
    current_attempts.any?(&:succes)
  end

  def incorrect_attempt?(participation)
    current_attempts.flat_map(&:participation).include?(participation)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include Broadcastable

  def show
    @game = Game.find(params[:id])

    unless @game.players.include?(current_user)
      Participation.create(user: current_user, game: @game, ready: false)
    end

    broadcast_players_list
  end

  def create
    @game = Game.new(user: current_user)
    @game.questions = Question.all.sample(60)
    @game.save

    redirect_to game_path(@game)
  end

  def start
    @game = Game.find(params[:id])
    @game.update(status: 'running')
    broadcast_remove_players_list
    broadcast_question
    broadcast_scores
    broadcast_timer
  end

  # def end
  #   @game = Game.find(params[:id])
  #   @game.update(status: 'ended')
  #   broadcast_summary
  # end

  def next_question
    @game = Game.find(params[:id])
    @game.question_number += 1
    @game.save
    broadcast_question
    broadcast_scores
    broadcast_timer
  end
end

app/views/games/_answer.html.erb
<div data-controller="solution"></div>

app/views/games/_desk.html.erb
<% previous_game_question =  GameQuestion.find_by(question:participation.game.previous_question, game: participation.game ) %>
<% previous_question_attempt = Attempt.find_by(participation: participation, game_question: previous_game_question) %>

<% current_game_question =  GameQuestion.find_by(question:participation.game.current_question, game: participation.game ) %>
<% current_question_attempt = Attempt.find_by(participation: participation, game_question: current_game_question) %>

<% flash_condition = previous_question_attempt && previous_question_attempt.success && current_question_attempt.nil? %>

<div id="player-desk-1round" data-controller="desk"
  data-desk-user-id-value="<%= participation.user.id %>"

  data-desk-points-value="<%= flash_condition ? participation.game.previous_question.point_value : 0 %>"
  data-desk-previous-value="<%= participation.game.previous_attempts.find { |at| at.success }&.participation == participation %>">


  <%= cl_image_tag participation.user.photo.key %>
  <p id="player-nickname-1round"><%= participation.user.nickname %></p>

  <div id="<%= participation.game.incorrect_attempt?(participation) ? 'card-point-1round-looser' : 'card-point-1round' %>">
    <% (9 - participation.point).times do %>
      <p class="point-1round-gray"></p>
    <% end %>

    <% (participation.point).times do |point| %>
      <p class="point-1round-orange"></p>
    <% end %>
  </div>
</div>

app/views/games/_players.html.erb
<div id="sas">
  <% unless user.find_participation(game).ready? %>
    <div class="focus">
      <div class="focus--mask">
        <p class="focus--mask-inner">Waiting</p>
      </div>
    </div>
  <% end %>

  <div class="card-players">
    <% players.order(:id).each do |player| %>
      <div class="fa-stack fa-1x card-player";>
        <% if game.user == player && player.find_participation(game).ready? %>
          <div class="card-player-inside" id="owner">
            <%= cl_image_tag player.photo.key, class:"avatar-sas" %>
            <p><%= player.nickname %></p>
            <span>
              <i class="fa fa-check check"></i>
            </span>
          </div>
        <% elsif player.find_participation(game).ready? %>
          <div class="card-player-inside">
            <%= cl_image_tag player.photo.key, class:"avatar-sas" %>
            <p><%= player.nickname %> <span><i class="fa fa-check check flip"></i></span></p>
          </div>
        <% else %>
          <div class="card-player-inside">
            <%= cl_image_tag player.photo.key, class:"avatar-sas" %>
            <p><%= player.nickname %></p>
          </div>
        <% end %>
        <% if user == player %>
          <% unless user.find_participation(game).ready? %>
            <%= link_to "Rejoindre", ready_participation_path(user.find_participation(game)), data: { turbo_method: :post }, id:"test", class:"little-orange-btn" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div>
    <% if game.players_ready? && game.user == user %>
      <%= link_to "Démarrer", start_game_path(game), class:"little-yellow-btn", data: { turbo_method: :post } %>
    <% end %>
  </div>

</div>

app/views/games/_question.html.erb
<div class="game">
  <div class="block-questions">
  <div class="question-point">
    <p><%= "#{question.point_value} pt" %></p>
  </div>
  <div class="question">
    <%= question.content %>
  </div>
    <div class="block-answers" data-controller="listener">
      <ul class="flex-container answers" data-answer-target="listButton">
        <% question.answers.shuffle.each do |answer| %>
          <div class="flex-content" id="choice" data-answer-target="input">
          <%# <button id="clicktest" data-action="click->listener#ouioui" data-listener-target="clicktest">test</button> %>
            <li class= "answer" id="<%= "correct" if answer.correct? %>"
                data-action="click->answer#revealAnswer <%= answer.correct? ? "click->listener#yes" : "click->listener#no" %>"
                data-answer-answer-id-param="<%= answer.id %>">

              <%= link_to answer.content, answer_participation_path(answer), data: { turbo_method: :post } %>
            </li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/games/_scores.html.erb
<div class="game">
  <div id="players-desk-1round">
    <% participations.order(:id).each do |participation| %>
      <div class="participation" id="participation_<%= participation.id %>">
        <%= render "games/desk", participation: participation %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_summary.html.erb
<div class="summary" data-controller="js-confetti">

  <% participations.each do |participation| %>
    <% if participation.point >= 9 %>
      <div class="winner">
        <%= image_tag "gif/winner.png"%>
        <p id="winner-name"><%= participation.user.nickname %></p>
        <%= image_tag "avatar/#{participation.user.photo.filename}.png", id:"avatar-winner"%>
      </div>
    <% end %>
  <% end %>

  <%= link_to "Rejouer",root_path, class:"little-yellow-btn" %>
</div>

app/views/games/_timer.html.erb
<div class="timer <%= "d-none" if state == "paused" %>" data-controller="timer" data-timer-game-id-value="<%= game.id %>" data-timer-state-value="<%=state%>" data-timer-time-value="1200">
  15
</div>

app/views/games/ready.html.erb
<h1>Games#is_ready</h1>
<p>Find me in app/views/games/is_ready.html.erb</p>

app/views/games/show.html.erb
<%= turbo_stream_from @game %>
<%= turbo_stream_from current_user %>

<div id="game-show" data-controller="answer" data-answer-participation-id-value="<%= current_user.find_participation(@game).id %>" data-user-id="<%= current_user.id %>">
  <div class="container" id="game">
    <% unless @game.started? || @game.ended? %>
      <div id="players">
        <%= render "games/players", players: @game.players, game: @game, user: current_user %>
      </div>
    <% end %>

      <div id="timer" data-controller="gamestart" class="<%= "owner" if current_user == @game.user %>">
        <% if @game.started? %>
          <%= render "games/timer", state: "running", game: @game %>
        <% end %>
      </div>

    <div id="question">
      <% if @game.started? && @game.current_question %>
        <%= render "games/question", question: @game.current_question %>
      <% end %>
    </div>

    <div id="answer">
      <% if @game.started? %>

      <% end %>
    </div>

    <div id="scores">
      <% if @game.started? %>
        <%= render "games/scores", participations: @game.participations, looser: false %>
      <% end %>
    </div>

    <div id="summary">
      <% if @game.ended? %>
        <%= render "games/summary", participations: @game.participations, looser: false %>
      <% end %>
    </div>
    </div>
  </div>

  </div>
</div>